### ISSUE TITLE
添加条件分支后再选择审批人报错。

### ISSUE THREAD

**Issue by ahua772** [go-workflow/go-workflow-UI#1]
![1581918430462](https://user-images.githubusercontent.com/19209280/74626859-0dfa4c00-518c-11ea-8b55-afc73788bfeb.jpg)

选择一个分支条件，再点击审批人报错：Error in v-on handler: "TypeError: Cannot read property 'prevId' of undefined"，
不懂前端，麻烦帮忙看看。
我是下载源码后，修改entry为main.js，npm i，npm run serve这样启动运行的。没看懂前面那三个步骤

**Comment by wzkun** [comment]
我也是遇到这个问题

**Comment by 56333178** [comment]
添加分支后无法添加审批人，求大大快点解决

**Comment by gelove** [comment]
改一下源码
component/Generator/condition-node-box.vue
第65行修改为如下
```
addnode (node) {
      this.$emit('addnode', node)
    },
```

**Comment by mumushuiding** [comment]
gelove 同学解决了部分问题

还有渲染问题，已经解决，详细修改可查阅2020.6.24的修改日志：

https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md
