### ISSUE TITLE
新增节点、移除节点，多执行几次，会出现数据错乱。

### ISSUE THREAD

**Issue by Royalzxl** [go-workflow/go-workflow-UI#4]
原因是process.js里面的iteratorData方法有问题 应该直接去掉这段代码
`if (temp.type === 'route') {
      resultArr.push(temp)
    } else {
      var item = {
        nodeId: temp.nodeId,
        name: temp.name,
        type: temp.type,
        properties: temp.properties
      }
      resultArr.push(item)
    }` 
在相同的位置加入
`resultArr.push(temp)`

**Comment by mumushuiding** [comment]
是由于没有正确渲染问题，已经解决，详细修改可查阅2020.6.24的修改日志：

https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md
