### ISSUE TITLE
中间穿插节点会导致页面紊乱

### ISSUE THREAD

**Issue by gl1355873614** [go-workflow/go-workflow-UI#5]
弄了好久都弄不出来；有没有大神指点一下

**Comment by mumushuiding** [comment]
插件源码地址：https://github.com/go-workflow/workflow-ui

问题已经修复

**Comment by gl1355873614** [comment]
大神，能不能说下怎么修复的，改动太多不能重新拉了...

**Comment by gl1355873614** [comment]
我试了你新的工作流，还是不行啊；
是节点与节点中间加节点会胡乱渲染（比如两个审批人中间加个抄送人，会乱显示）
![image](https://user-images.githubusercontent.com/29000548/85512132-2099fb80-b62c-11ea-8024-a683feb74103.png)

**Comment by mumushuiding** [comment]
是由于没有正确渲染问题，已经解决，详细修改可查阅2020.6.24的修改日志：

https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md

**Comment by mumushuiding** [comment]
之前应该是解决了不能添加的问题，你说的是添加混乱问题，这是由于页面没有刷新的关系，解决方法看链接


https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md&nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gl1355873614"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午3:06
收件人: "go-workflow/go-workflow-UI"<go-workflow-UI@noreply.github.com&gt;; 
抄送: "涤生"<181457121@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [go-workflow/go-workflow-UI] 中间穿插节点会导致页面紊乱 (#5)





 
我试了你新的工作流，还是不行啊；
 是节点与节点中间加节点会胡乱渲染（比如两个审批人中间加个抄送人，会乱显示）

**Comment by gl1355873614** [comment]
谢谢大神 我正在照着改



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "go"<notifications@github.com&gt;; 
发送时间: 2020年6月24日(星期三) 下午4:29
收件人: "go-workflow/go-workflow-UI"<go-workflow-UI@noreply.github.com&gt;; 
抄送: "心忘、何所忆"<1355873614@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [go-workflow/go-workflow-UI] 中间穿插节点会导致页面紊乱 (#5)





 之前应该是解决了不能添加的问题，你说的是添加混乱问题，这是由于页面没有刷新的关系，解决方法看链接 
 
 
 https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md&amp;amp;nbsp;&amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "gl1355873614"<notifications@github.com&amp;gt;;  
 发送时间: 2020年6月24日(星期三) 下午3:06 
 收件人: "go-workflow/go-workflow-UI"<go-workflow-UI@noreply.github.com&amp;gt;;  
 抄送: "涤生"<181457121@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;  
 主题: Re: [go-workflow/go-workflow-UI] 中间穿插节点会导致页面紊乱 (#5) 
 
 
 
 
 
   
 我试了你新的工作流，还是不行啊； 
  是节点与节点中间加节点会胡乱渲染（比如两个审批人中间加个抄送人，会乱显示）
