### ISSUE TITLE
节点中间插节点会乱渲染（详细见图）

### ISSUE THREAD

**Issue by gl1355873614** [go-workflow/go-workflow-UI#6]
![image](https://user-images.githubusercontent.com/29000548/85512454-8090a200-b62c-11ea-8390-9dccab219bb5.png)

**Comment by mumushuiding** [comment]
是由于没有正确渲染问题，已经解决，详细修改可查阅2020.6.24的修改日志：

https://github.com/go-workflow/workflow-ui/blob/master/%E7%BB%B4%E6%8A%A4%E6%97%A5%E5%BF%97.md
